name: Request and Print

on:
  workflow_dispatch:

jobs:
  request_and_print:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET requests to URLs
        run: |
          echo "Requesting https://example.com"
          curl -vv -k --max-time 10 https://example.com
